import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import BG from '../assets/bg.png'
import CardImg from '../assets/card.jpg'

import Nav from './nav'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main>
        <nav className='nav'>
          <div className="nav-title">Navbar</div>
          <button className="btn">로그인</button>
        </nav>

        <div className="bg"></div>

        <div className="bg-info">
          <div className="bg-info-text">이번 분기의 인기 애니를 확인해보세요</div>
          <button className="btn">확인하러 가기</button>
        </div>

        <div className="cards">
          <div className="card-contain">
            <div className="card">
              <Image className='card-img' src={ CardImg } alt='' />
              <div className="card-title">원신하고싶다</div>
            </div>

            <div className="card">
              <Image className='card-img' src={ CardImg } alt='' />
              <div className="card-title">원신하고싶다</div>
            </div>

            <div className="card">
              <Image className='card-img' src={ CardImg } alt='' />
              <div className="card-title">원신하고싶다</div>
            </div>

            <div className="card">
              <Image className='card-img' src={ CardImg } alt='' />
              <div className="card-title">원신하고싶다</div>
            </div>

            <div className="card">
              <Image className='card-img' src={ CardImg } alt='' />
              <div className="card-title">원신하고싶다</div>
            </div>

            <div className="card">
              <Image className='card-img' src={ CardImg } alt='' />
              <div className="card-title">원신하고싶다</div>
            </div>
          </div>
        </div>

      </main>
    </>
  )
}
